### ISSUE TITLE
Current release (0.0.12) high level vulnerabilities

### ISSUE THREAD

**Issue by themoosman** [redhat-cop/group-sync-operator#121]
The current version of the operator `0.0.12` has 2 high and 18 medium vulnerabilities.  

https://quay.io/repository/redhat-cop/group-sync-operator/manifest/sha256:fd51dd413cfe6d6929e7b57f865b1c8b99ac9e17c9deed3dfa86b46d8b375b9f?tab=vulnerabilities

**Comment by sabre1041** [comment]
@themoosman there is planned to be a release today/tomorrow (sept 1/sept 2) to `0.0.13`. hopefully that will resolve the concerns

**Comment by themoosman** [comment]
Great, I'll test when it is released and close the issue if it fixes the issue.

**Comment by themoosman** [comment]
Confirmed fixed in `v0.0.13`
