### ISSUE TITLE
Documentation mistakes

### ISSUE THREAD

**Issue by Edenzil** [redhat-cop/group-sync-operator#130]
Hi i deployed the operator for keycloak and found some mistakes in the document. 

In the ca certificate section, the example isnt right. 
In the command that creates the secret the name of the key is ca.crt, but in the continued yaml the name of the key is tls.crt .

Next in the section that creates the user who needs to authenticate to keycloak, it mentions to add permissions in the master realm or realm-managment. Please add in this sentence that you need to add the rules in the realm that the groups located at.

**Comment by sabre1041** [comment]
@Edenzil a number of change were made recently. can you check to see if the latest documentation accounts for the necessary configurations needed to configure the operator?

**Comment by sabre1041** [comment]
Closing as documentation has been updated
