### ISSUE TITLE
Group Provider Label Did Not Match Expected Provider LabelGroup Name

### ISSUE THREAD

**Issue by cchen666** [redhat-cop/group-sync-operator#133]
time="2021-10-19T13:54:38Z" level=info msg="Group Provider Label Did Not Match Expected Provider LabelGroup Nameocp_adminExpected Labelldap-groupsync_ldapFound Label" source="groupsync_controller.go:140"

Seems there is no step to label a group in this operator README. According to the message, seems my group in ldap "ocp_admin" will not be synced because the label mismatch. It should have the label called ldap-groupsync_ldap but the fact is, it doesn't have any label.

This group is synced manually before but when trying to sync it using group-sync-operator seems it is skipped ?

**Comment by sabre1041** [comment]
Existing groups are not managed via the operator. If the group exists that you would like to sync, delete the group and the operator should resync

**Comment by sabre1041** [comment]
Closing due to staleness
