### ISSUE TITLE
proprietary container image referenced in current release (v0.0.14)

### ISSUE THREAD

**Issue by nate-duke** [redhat-cop/group-sync-operator#143]
See: https://github.com/redhat-cop/group-sync-operator/blob/v0.0.14/config/default/manager_auth_proxy_patch.yaml#L13

This results in an image pull failures for okd clusters which try to install this operator. This seems to be fixed in #137 but that hasn't been included in a release yet.

**Comment by sabre1041** [comment]
@nate-duke we are in the process of updating our release pipeline and then we can push out a new release.

**Comment by sabre1041** [comment]
@nate-duke 0.0.15 has been released. can you verify the image has been updated as expected?

**Comment by nate-duke** [comment]
Looks like we picked it up on our dev clusters in the most recent update. Thank you for looking into it. the Containers are both now specified with images coming from quay.io.

Thank you for taking care of this operator. You've saved, well at least me, from a giant ball of custom python code to perform this task! ;)
