### ISSUE TITLE
Avoid problematic language 

### ISSUE THREAD

**Issue by testlaben** [redhat-cop/group-sync-operator#157]
https://www.redhat.com/en/blog/making-open-source-more-inclusive-eradicating-problematic-language

**Comment by sabre1041** [comment]
@testlaben I truly agree. However, the some of the language that you are referencing is being inherited through OpenShift's ldap libraries. The change would need to occur upstream first

**Comment by sabre1041** [comment]
Closing as this issue is not an item that can be handled by the operator at this time
