### ISSUE TITLE
CA Certificates as ConfigMap instead of Secret

### ISSUE THREAD

**Issue by ocpvkb** [redhat-cop/group-sync-operator#158]
CA Certificates or trust bundles do not have to store as a secret.
The information is not worth protecting.
The default strategie for this is a ConfigMap. With this implemantation the operator gets closer to the mainstream.
Also the usage of injection by Operators will be possible.
e.g. the Cluster Network Operator
(metadata.labels -->config.openshift.io/inject-trusted-cabundle="true")

**Comment by sabre1041** [comment]
@ocpvkb This is a good enhancement. ideally, we should attempt to support both use cases of providing a `Secret` or `ConfigMap`. Initial thoughts are to introduce a new field `ca` that allows for defining either a `Secret` or `ConfigMap`. We can then deprecate the existing `caSecret` field and remove several versions in the future.

Thoughts?

**Comment by ocpvkb** [comment]
Thank you for the fast implementation. :-)
The changes look valid.

**Comment by sabre1041** [comment]
@ocpvkb its been a longterm ask. This put it over the hump to knock out
