### ISSUE TITLE
Scheduling doesn't work as expected for azure-groupsync

### ISSUE THREAD

**Issue by SIDDHARTH2306** [redhat-cop/group-sync-operator#170]
We are trying to sync groups from azure aad in a specific time interval. But the scheduling is not working as expected. We tried manipulating it with a lesser time interval i.e. 5 mins and 10 mins but it doesn't trigger at that interval. In fact, it takes around 1 hour or more to rerun. I try reloading the YAML but see no change.

**Comment by sabre1041** [comment]
@SIDDHARTH2306 Can you provide your custom resource?

**Comment by sabre1041** [comment]
Closing due to lack of feedback
