### ISSUE TITLE
kube-rbac-proxy leaks service account tokens

### ISSUE THREAD

**Issue by skuffe** [redhat-cop/group-sync-operator#216]
It seems that the included kube-rbac-proxy has its log verbosity set to a really high level, and thus it dumps the service account token that prometheus uses to authenticate itself with directly to stdout, when being monitored in OpenShift.

![image](https://user-images.githubusercontent.com/1579080/192504828-c667c0e2-88bb-4f65-a775-5a28f7b9e452.png)

> I0927 10:31:17.035179       1 request.go:1097] Request Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/metrics","verb":"get"},"user":"system:serviceaccount:openshift-monitoring:prometheus-k8s","groups":["system:serviceaccounts","system:serviceaccounts:openshift-monitoring","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["prometheus-k8s-1"],"authentication.kubernetes.io/pod-uid":["4e605640-46df-45e4-bf3b-31b23d1fa8ab"]},"uid":"0e16d7ee-5251-430f-aade-f87fe97e10eb"},"status":{"allowed":false}}
I0927 10:31:17.035467       1 round_trippers.go:423] curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "User-Agent: kube-rbac-proxy/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer **_eyJhbGciOiJSUzI1NiIsImtpZCI6InFzLTd5OGs4YVczYU <*redacted*>_**" 'https://<*redacted*>:443/apis/authorization.k8s.io/v1/subjectaccessreviews'
I0927 10:31:17.039552       1 round_trippers.go:443] POST https://<*redacted*>:443/apis/authorization.k8s.io/v1/subjectaccessreviews 201 Created in 4 milliseconds
I0927 10:31:17.039583       1 round_trippers.go:449] Response Headers:
I0927 10:31:17.039589       1 round_trippers.go:452]     X-Kubernetes-Pf-Prioritylevel-Uid: 53bcb8be-186b-494d-ac80-73559dace745
I0927 10:31:17.039592       1 round_trippers.go:452]     Content-Length: 1152
I0927 10:31:17.039595       1 round_trippers.go:452]     Date: Tue, 27 Sep 2022 10:31:17 GMT
I0927 10:31:17.039598       1 round_trippers.go:452]     Audit-Id: 7ec2b535-8302-4610-99a3-5c08b99b688b
I0927 10:31:17.039601       1 round_trippers.go:452]     Cache-Control: no-cache, private
I0927 10:31:17.039604       1 round_trippers.go:452]     Content-Type: application/json
I0927 10:31:17.039607       1 round_trippers.go:452]     X-Kubernetes-Pf-Flowschema-Uid: 3cf798fa-bbf6-47bf-9a06-dcae26e3c37b
I0927 10:31:17.039639       1 request.go:1097] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null,"managedFields":[{"manager":"kube-rbac-proxy","operation":"Update","apiVersion":"authorization.k8s.io/v1","time":"2022-09-27T10:31:17Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:extra":{".":{},"f:authentication.kubernetes.io/pod-name":{},"f:authentication.kubernetes.io/pod-uid":{}},"f:groups":{},"f:nonResourceAttributes":{".":{},"f:path":{},"f:verb":{}},"f:uid":{},"f:user":{}}}}]},"spec":{"nonResourceAttributes":{"path":"/metrics","verb":"get"},"user":"system:serviceaccount:openshift-monitoring:prometheus-k8s","groups":["system:serviceaccounts","system:serviceaccounts:openshift-monitoring","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["prometheus-k8s-1"],"authentication.kubernetes.io/pod-uid":["4e605640-46df-45e4-bf3b-31b23d1fa8ab"]},"uid":"0e16d7ee-5251-430f-aade-f87fe97e10eb"},"status":{"allowed":true,"reason":"RBAC: allowed by ClusterRoleBinding \"clusterlogging-collector-metrics\" of ClusterRole \"clusterlogging-collector-metrics\" to ServiceAccount \"prometheus-k8s/openshift-monitoring\""}}

It appears to be hard coded in the manifest, with no handles to adjust the level.
This is a potential security issue, as logs are often shipped to external systems and pod output could be potentially be readable by other users, inadvertently giving them access to the cluster on behalf of Prometheus.

My suggestion would be to lower the log level to something more reasonable by default, or perhaps make it configurable?

**Comment by GerbenWelter** [comment]
Can we please get a new operator release with this logging parameter removed? It seems to be a left over from some testing and it's absolutely spamming the kube-rbac-proxy console and therefor putting unneeded strain on everything that captures this log.

**Comment by sabre1041** [comment]
@GerbenWelter submitted #226
