### ISSUE TITLE
RH Operator hub installation fails with unsatisfied requirement 

### ISSUE THREAD

**Issue by reggie-k** [redhat-cop/group-sync-operator#228]
Trying to install 0.0.20 with operator hub, received an error that the controller-manager sa is not found. Looks like it is not packed in the manifests, or packed with a different name.
I created it myself in the ns, but received the next error about rbac policyrules not satisfied.
Unable to install using operator hub.

Please provide me with a quick way to find all the manifests needed for installing by myself without operator hub, as we have upgraded ocp and need to upgrade the operator urgently.
I am OK with either plain manifests, helm or kustomize, just need them to be complete.

**Comment by sabre1041** [comment]
Can you uninstall the operator and reinstall it? I have installed it recently without issue on the most recent OpenShift version 4.11

**Comment by reggie-k** [comment]
We have tried that. The same error about controller-manager sa that is
missing.
But we run on 4.10, wonder whether that matters? Do you have a 4.10 to test
against? Or shall I install an earlier operator version for 4.10?

**Comment by sabre1041** [comment]
I just installed the Operator from OperatorHub on a fresh 4.10.36

**Comment by sabre1041** [comment]
@reggie-k yes

**Comment by reggie-k** [comment]
Till I figure out what happens with the operator hub, what would be the
quickest way to install the operator without it
?

**Comment by reggie-k** [comment]
I found the problem and now able to install with operator hub, my bad.
It looks like our previous crd was not deleted and caused problems during
installation. Now deleted and able to install using Operator Hub.
Thanks a lot for your assistance!
