### ISSUE TITLE
"Insecure" in schema is ignored for Azure provider

### ISSUE THREAD

**Issue by andymiller96** [redhat-cop/group-sync-operator#233]
Multiple providers have an "Insecure" bool for skipping certificate verifications. Azure has this as part of the current schema however, this property is ignored. 

Property refs for Azure:
1. https://github.com/redhat-cop/group-sync-operator/blob/main/config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml#L80-L82 
2. https://github.com/redhat-cop/group-sync-operator/blob/main/api/v1alpha1/groupsync_types.go#L378-L381

**Comment by sabre1041** [comment]
Feature has been implemented
