### ISSUE TITLE
configmaps lock is removed, migrate to configmapsleases

### ISSUE THREAD

**Issue by louise-zhang** [redhat-cop/group-sync-operator#234]
CSV group-sync-operator.v0.0.21 install cannot be completed due to the below error:

unable to start manager {"error": "configmaps lock is removed, migrate to configmapsleases"}

![image](https://user-images.githubusercontent.com/48479569/208542169-cbfc076f-9cc0-4f9e-9040-201700d2e9ef.png)

ARO version: 4.10.15
Group sync operator: alpha: group-sync-operator.v0.0.21
group-sync-operator image: quay.io/redhat-cop/group-sync-operator@sha256:979acc20b045f1b21c5bb60bc3d95ed5ccb440d93eef9a4cbb19751d8922a83d

**Comment by koolrays** [comment]
Also seeing same issue. 
ARO Version: 4.10.30
Group sync operator: alpha: group-sync-operator.v0.0.21
group-sync-operator image: quay.io/redhat-cop/group-sync-operator@sha256:979acc20b045f1b21c5bb60bc3d95ed5ccb440d93eef9a4cbb19751d8922a83d

**Comment by sabre1041** [comment]
Issue acknowledged. Investigating....

**Comment by vmospan-hub** [comment]
Hi. When can we expect a new release with a fix?

**Comment by sabre1041** [comment]
@vmospan-hub New release was just published and is being processed by the OperatorHub team

Release: https://github.com/redhat-cop/group-sync-operator/releases/tag/v0.0.22
Operator Hub PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1984

**Comment by vmospan-hub** [comment]
Thanks!

**Comment by sabre1041** [comment]
0.0.22 should now be available in Operator Hub

**Comment by koolrays** [comment]
Thanks for the quick turn around.

**Comment by louise-zhang** [comment]
Thank you @sabre1041, it's working now

**Comment by ValentinoUberti** [comment]
Thank you, @sabre104. It's working here using OCP 4.11.18 with RH IDM.

**Comment by prgss** [comment]
@EirikOpheim , we were in the same situation.

We removed both 0.0.21 and 0.0.20 and after that you can install again from scratch with 0.0.25 version.

![image](https://github.com/redhat-cop/group-sync-operator/assets/67279457/5af6aa5c-d821-4e57-a74b-143472b7096f)

Now the pod is running well.


Maybe there is an issue in the upgrade path, we should be able to bypass the 0.0.21 version when upgrading from 0.0.20
