### ISSUE TITLE
Update 0.0.21 on 12/19 getting errors with "ERROR	setup	unable to start manager	{"error": "configmaps lock is removed, migrate to configmapsleases"}"

### ISSUE THREAD

**Issue by u849296** [redhat-cop/group-sync-operator#236]
I1219 21:21:45.004090       1 request.go:601] Waited for 1.034362795s due to client-side throttling, not priority and fairness, request: GET:https://100.65.0.1:443/apis/hiveinternal.openshift.io/v1alpha1?timeout=32s
1.6714849103101313e+09	ERROR	setup	unable to start manager	{"error": "configmaps lock is removed, migrate to configmapsleases"}
main.main
	/home/runner/work/group-sync-operator/group-sync-operator/main.go:78
runtime.main
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/proc.go:250

I have 3x Openshift 4.11 all were working with 0.0.20 and now the pod does not start.  I also tried a fresh install using the operator but same error.  At this point I cannot add/rm Azure AD groups to my OCP systems.

**Comment by sabre1041** [comment]
please see #234 

New release should be out today

**Comment by u849296** [comment]
Thanks for the quick update Andy!

**Comment by sabre1041** [comment]
0.0.22 should be available now

**Comment by sabre1041** [comment]
@u849296 when you get a chance to confirm the new version has no issues, would you be able to close the issue?
