### ISSUE TITLE
Upgrade to 0.0.21 is giving issue on OCP 4.10.30 

### ISSUE THREAD

**Issue by simplyvishal** [redhat-cop/group-sync-operator#243]
Hello Team,

I am working with of of client through Red hat .Currently we are on OCP4.10.30 and group-sync-operator operator version 0.0.20 everything good . Now we tried to upgrade to 0.0.21 and getting following error .

oc logs pod/group-sync-operator-controller-manager-bd778954b-v9rmt -c manager
I0105 18:20:37.960398       1 request.go:601] Waited for 1.038121369s due to client-side throttling, not priority and fairness, request: GET:[https://x.x.x.x:443/apis/apps.openshift.io/v1?timeout=32s](https://x.x.x.x/apis/apps.openshift.io/v1?timeout=32s)
1.6729428410230706e+09  ERROR   setup   unable to start manager {"error": "configmaps lock is removed, migrate to configmapsleases"}

In past with other community operator i have seen this issue which was addressed by changing matchPolicy:Equivalent .is anything similar change we need to do for new version . OR any help you can provide to address same .

Thanks 
Vishal Chaudhary

**Comment by sabre1041** [comment]
Please upgrade to 0.0.23 as it contains the fix

https://github.com/redhat-cop/group-sync-operator/issues/237

**Comment by simplyvishal** [comment]
Thanks will try that and let you know outcomes .

**Comment by bergethon** [comment]
+1, updating to 0.0.23 resolved the issue.

**Comment by sabre1041** [comment]
@simplyvishal did updating resolve the issue you were facing?

**Comment by simplyvishal** [comment]
Issue is solved after 0.0.23

**Comment by sabre1041** [comment]
Closing as issue was resolved
