### ISSUE TITLE
Azure - member limitation of 100

### ISSUE THREAD

**Issue by dortlii** [redhat-cop/group-sync-operator#246]
We are using the operator (version 0.0.23) on OpenShift 4.10.43 and syncing some Azure AD groups. We have 2 large groups with 100+ members (a big project and a `common` group) and in OpenShift we only find 100 from e.g. 123 members.

Is there a limit which we can adjust? If not, what could be a good solution for our 2 biggest groups? We are syncing a lot of groups (probably around 230) and only these 2 are causing problems.

The operator status is fine and syncing every 5 min as configured. The `manager` container from the `group-sync-operator-controller-manager` doesn't show any errors. Is this an already known issue / limitation?

**Comment by sabre1041** [comment]
@dortlii ive acknowledged the bug. looking into a resolution

**Comment by sabre1041** [comment]
@dortlii looked into the issue. Ultimately, I was unable to find the foolproof solution at this time. However, an increase to the page size was made to the maximum allowed by the Azure graph API (999 items) which should cover your use case.

**Comment by dortlii** [comment]
@sabre1041 perfect, as soon as we can test this with the page size increased, I will updated this issue. Thanks for taking a look at it.

**Comment by MoazHafeez** [comment]
Hi all, Did this get resolved and tested?
I am having the same issue:
operator (version 0.0.28) on OpenShift 4.12.51

**Comment by sabre1041** [comment]
> @sabre1041 does anything need to be configured on either the operator, instance or Azure side to increase the page size?

#313 was just submitted to address providing a pagesize to all queries to Azure. It is the hope that it addresses the issues that you are currently facing
