### ISSUE TITLE
Add documentation to setup RHSSO user with minimum required permissions

### ISSUE THREAD

**Issue by ghurel-rh** [redhat-cop/group-sync-operator#26]
For security purposes, it is better to use a permission-limited user in RHSSO for the group-sync-operator.

To do so (mostly from https://stackoverflow.com/questions/56743109/keycloak-create-admin-user-in-a-realm):

1. Open RHSSO admin console and select realm of your choice (realm selection box on top left side)
2. Go to users (sidebar) -> add user (button on the right side)
3. Fill in required fields and press save button.
4. Open the Credentials tab and set a password; be sure to disable the "Temporary" switch
5. Open Role Mapping tab
6. Select realm-management under Client Roles.
7. Select query-groups and query-users roles

You can then use this account by creating the asscotiated secret in OCP and use it for the GroupSync CR:
```
$ oc create secret generic keycloak-group-sync --from-literal=username=group-sync-user --from-literal=password=group-sync-password
$ cat groupsync.yaml
  [...]
  - keycloak:
      credentialsSecret:
        name: keycloak-group-sync
        namespace: < groupsync-operator-namespace >
      loginRealm: < the selected realm >
      realm: < the selected realm >
   [...]
```

**Comment by sabre1041** [comment]
@ghurel-rh this is good. 

Maybe we create a separate more thorough set of documentation that expands on each provider and walks through each step in detail. For some providers, such as AzureAD, there are a bunch of prerequisites in order to create the App Registration

Any interest in taking a shot at Keycloak?

**Comment by sabre1041** [comment]
@ghurel-rh Additional documentation has been added to cover this issue
