### ISSUE TITLE
group-sync-operator missing from OperatorHub.io

### ISSUE THREAD

**Issue by trexx** [redhat-cop/group-sync-operator#307]
Hi there,

Our group-sync-operator subscription is reporting

```
ConstraintsNotSatisfiable
constraints not satisfiable: subscription group-sync-operator exists, no operators found in package group-sync-operator in the catalog referenced by subscription group-sync-operator
```

Trying to search in operatorhub.io results in no hits. Has something gone missing?

Our subscription looks like the same configured in the repo here:

```
  channel: alpha
  installPlanApproval: Manual
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
```

I can however find it on the developer instance of OperatorHub.io
https://dev.operatorhub.io/operator/group-sync-operator

**Comment by sabre1041** [comment]
@trexx This operator has never been published to operatorhub.io
