### ISSUE TITLE
Azure - groups filter being ignored

### ISSUE THREAD

**Issue by MikeSkuseN** [redhat-cop/group-sync-operator#32]
When deploying group-sync-operator 0.0.5 against using Azure provider per below config and 'groups' specification is being ignored and all groups are being synced from AzureAD rather than the one(s) specified

apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: azure-groupsync
spec:
  providers:
  - name: azure
    azure:
      credentialsSecret:
        name: azure-group-sync
        namespace: group-sync-operator
      groups:
        - testgroupname
  schedule: '* * * * *'

**Comment by aglenn360** [comment]
it looks like no logic has been added to the azure syncer to handle provider.groups as an option, needs something similar to the below

func (g *GitLabSyncer) Sync() ([]userv1.Group, error) {

	ocpGroups := []userv1.Group{}

	groups, err := g.getGroups()

	if err != nil {
		return nil, err
	}

	for _, group := range groups {

		if !isGroupAllowed(group.Name, g.Provider.Groups) {
			continue
		}

		groupMembers, err := g.getGroupMembers(group.ID)

		if err != nil {
			return nil, err
		}

I think which is in the gitlab syncer, this is missing from a few of the syncers

**Comment by sabre1041** [comment]
@aglenn360 @MikeSkuseN thanks for calling this out. I'll look into it
