### ISSUE TITLE
Group Sync 0.0.29 fails to upgrade and install

### ISSUE THREAD

**Issue by adam63redhat** [redhat-cop/group-sync-operator#323]
Upgrade fails with:

```
    - lastTransitionTime: '2024-07-26T02:20:28Z'
      lastUpdateTime: '2024-07-26T02:20:28Z'
      message: >-
        install strategy failed: Deployment.apps
        "group-sync-operator-controller-manager" is invalid: spec.selector:
        Invalid value:
        v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"group-sync-operator"},
        MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
      phase: Failed
      reason: InstallComponentFailed
```

Install fails because the deployment can't find serviceaccount `group-sync-operator`

Install succeeds after creating the serviceaccount. Upgrade succeeds if the service account is in place and the prior 0.0.28 CSV is deleted.

**Comment by sabre1041** [comment]
Looking into this now. Will most likely bleed into Friday for a resolution

**Comment by sabre1041** [comment]
@adam63redhat `v0.0.30` has been push and will be released soon. Apologies for the issues with the most recent release

**Comment by fager** [comment]
Thanks for the quick bug fix.

It's refreshing to find the bug fix right after the first error message.

Is there already an instruction on how to install 0.0.30? Currently 0.0.28 is in the Replacing status and 0.0.30 is stuck in a Pending/InstallReadyFailed loop...

**Comment by paulgilbody** [comment]
> Thanks for the quick bug fix.
> 
> It's refreshing to find the bug fix right after the first error message.
> 
> Is there already an instruction on how to install 0.0.30? Currently 0.0.28 is in the Replacing status and 0.0.29 is stuck in a Pending/InstallReadyFailed loop...

delete 0.0.28 CSV (include dependents)
wait for 5 mins until 0.0.30 appears (0.0.29 only has uninstall rather than delete csv option until then which will not complete - do not choose uninstall)
once 0.0.30 appears, delete 0.0.29
- then all good

**Comment by mohantyashutosh** [comment]
Hi, Thanks for the resolution but I see the same error after doing the steps you have mentioned.

install strategy failed: Deployment.apps "group-sync-operator-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"group-sync-operator"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by mohantyashutosh** [comment]
looks like the old deployment is still there, is there a way I can get this sorted?

installing: waiting for deployment group-sync-operator-controller-manager to become ready: deployment "group-sync-operator-controller-manager" not available: Deployment does not have minimum availability.

**Comment by sabre1041** [comment]
@mohantyashutosh did you uninstall the operator and then install version 0.0.30?

**Comment by mohantyashutosh** [comment]
> @mohantyashutosh did you uninstall the operator and then install version 0.0.30?

Yes I did uninstall 29 and then install 30.
