### ISSUE TITLE
[Azure] Change from Azure AD Graph API to Microsoft Graph API

### ISSUE THREAD

**Issue by marbindrakon** [redhat-cop/group-sync-operator#40]
The Azure Active Directory Graph API has been deprecated with the Microsoft Graph API as its replacement. The new API also provides more granular permissions (i.e. GroupMember.Read.All instead of requiring Directory.Read.All)

This issue is to track changing the Azure syncer to use the new API.

**Comment by sabre1041** [comment]
@marbindrakon This has been integrated into master as part of #44 and will be released soon
