### ISSUE TITLE
When trying LDAP rfc2307 synchronization with whitelist parameter, I get the error when syncing "Expected Label":"<metadata.name>_<spec_providers_ldap:name>,"Found Label":""}

### ISSUE THREAD

**Issue by MichaelGoldsbie** [redhat-cop/group-sync-operator#47]
I am trying to run the operator for **ldap**, specifically the **rfc2307** configuration, and using the whitelist parameter for an AD group.  However, I receive the following error in the log from the resulting pod:

`{"level":"info","ts":1606189207.9799204,"logger":"controller_groupsync","msg":"Group Provider Label Did Not Match Expected Provider Label","Group Name":"<AD_GROUP>","Expected Label":"ldap-groupsync_ldap","Found Label":""}
`

The underlying YML code to deploy the operator would be:

`apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: **ldap-groupsync**
spec:
  providers:
  - ldap:
      credentialsSecret:
        name: ldap-group-sync
        namespace: bmo-group-sync-operator
      insecure: true
      whitelist: 
       - <AD_GROUP>
      rfc2307:
        groupMembershipAttributes: [ member ]
        groupNameAttributes: [ cn ]
        groupUIDAttribute: cn
        groupsQuery:
          baseDN: "OU=<A>,OU=<B>,OU=<C>,OU=<D>,OU=<E>,DC=<F>,DC=<G>,DC=<H>,DC=net"
          derefAliases: never
          filter: (objectClass=group)
          scope: sub
          pageSize: 1000
        tolerateMemberNotFoundErrors: true
        tolerateMemberOutOfScopeErrors: true
        userNameAttributes: [ sAMAccountName ]
        userUIDAttribute: dn
        usersQuery:
          baseDN: "DC=<F>,DC=<G>,DC=<H>,DC=net"  
          derefAliases: never
          scope: sub
          pageSize: 1000
      url: <ldap_url>
    name: **ldap**
`

In the error above, I can see that when it says  "Expected Label":"ldap-groupsync_ldap", this value is a concatenation of

<metadata.name>_<spec_providers_ldap:name>

from the YML above, which I even proved before by adjusting their values and seeing their results.  I am unsure where these "label" values come from, as I don't know if this type of parameter exists in LDAP.  I'm wondering if it is an underlying issue with the operator itself?

Please let me know if more information is required.

Thanks,

Michael

**Comment by sabre1041** [comment]
The purpose of this label is to ensure that the operator has exclusive rights to the group in OpenShift.

Was this group already in OpenShift prior to the installation of the operator? If so, it will need to be removed. The synchronization will reestablish the group once complete.

Just a heads up that a newer release of the operator should be available in the next few days.

**Comment by MichaelGoldsbie** [comment]
Thanks, I tried removing the group and it ended up working successfully!

However, there's no way to synchronize the group without removing it first, right?  This could potentially pose a challenge on our end, as AD group memberships change all the time as new people join teams, or leave teams, etc., so up until now, our setup has been to run the command:

**oadm groups sync --whitelist=<whitelist_file>--sync-config=sync-config.yaml** 

And the underlying YAML file I supplied to this operator was largely based on the above sync-config.yaml.  This command has been run on a periodic basis so that Openshift's AD groups are constantly up to date, and if an AD group in the whitelist has its membership change at any point, this will get reflected at every sync, without first removing the group from Openshift, thus leaving no potential impact on users who already have access.  If we had to remove the group from Openshift in order to sync it again with Openshift if memberships change, then the people who are already members could lose access.  Is there any way around this?

**Comment by sabre1041** [comment]
If you want to run the following command, it will update all of the existing groups with the expected label and it should allow the operator to work when it reconciles

```
for group in `oc get groups -o name`; do oc label $group group-sync-operator.redhat-cop.io/sync-provider=ldap-groupsync_ldap; done
```

**Comment by MichaelGoldsbie** [comment]
Ahhh...yes, I tried something like that and it worked! Thanks so much!

**Comment by sabre1041** [comment]
Great! @MichaelGoldsbie would we be able to close the issue?

**Comment by MichaelGoldsbie** [comment]
Yes, this can be closed. :)  Thanks again!

**Comment by sabre1041** [comment]
Closing
