### ISSUE TITLE
Distribute via hub?

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-cop/group-sync-operator#48]
It would be nice to have versions distributed via operator-hub instead of having users having to compile etc themselves. WDYT?

**Comment by sabre1041** [comment]
@davidkarlsen This operator is available in OperatorHub
![Uploading Screen Shot 2020-12-07 at 1.28.51 PM.png…]()

**Comment by davidkarlsen** [comment]
Oh - I must be blind :-)
Will it be updated with 0.0.7?
Also - we need to go via http proxy - does the operator support passing env-vars?

**Comment by sabre1041** [comment]
@davidkarlsen the upstream pull request to make 0.0.7 available in OperatorHub was merged this morning (ironic)

https://github.com/operator-framework/community-operators/pull/2728

It should be available within the next few days

Regarding proxy support, it does not currently exist. It would need to be added as a new feature in the operator

**Comment by davidkarlsen** [comment]
Thanks. Closing. I'll create another issue for the env vars

**Comment by davidkarlsen** [comment]
I see it was merged - but still only the old 0.0.6 is available?
