### ISSUE TITLE
Use same registry for the images

### ISSUE THREAD

**Issue by MinorDudle** [redhat-cop/group-sync-operator#50]
kube-rbac-proxy container image is stored at gcr.io
https://github.com/redhat-cop/group-sync-operator/blob/master/config/default/manager_auth_proxy_patch.yaml#L13

manager container image is stored at quay.io registry.

As I noticed kube-rbac-proxy image is already pushed to one Red Hat registry, just older version.

@sabre1041 , could we change kube-rbac-proxy image source to other one which is in Red Hat registry?

**Comment by sabre1041** [comment]
@MinorDudle proxy is no longer being used.

**Comment by sabre1041** [comment]
Closing

**Comment by nate-duke** [comment]
https://github.com/redhat-cop/group-sync-operator/blob/v0.0.14/config/default/manager_auth_proxy_patch.yaml#L13
this seems to have regressed.
