### ISSUE TITLE
docs up to date?

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-cop/group-sync-operator#52]
https://github.com/redhat-cop/group-sync-operator#overview states "Currently, this functionality is limited to LDAP only." - but it is possible to configure for instance AD credentials. What does the controller do if it does not create groups?

**Comment by sabre1041** [comment]
this relates to existing OpenShift functionality. Not the operator

**Comment by davidkarlsen** [comment]
But will the operator create the groups or not when running on ocp?

**Comment by sabre1041** [comment]
Yes it will. That is the goal of the operator. Doc updates to clarify as part of #53

**Comment by davidkarlsen** [comment]
Maybe the sentence "Currently, this functionality is limited to LDAP only." should be dropped from the readme then?

**Comment by sabre1041** [comment]
@davidkarlsen README has been updated to read "Currently, the functionality that is included in OpenShift to limited to synchronizing LDAP only"

**Comment by sabre1041** [comment]
Closing as issue has been resolved
