### ISSUE TITLE
Cannot upgrade from 0.0.6 to 0.0.7 because ServiceAccount does not have RBAC policy rules

### ISSUE THREAD

**Issue by MichaelGoldsbie** [redhat-cop/group-sync-operator#54]
Hi Andrew,

Thank you very much for your help earlier in troubleshooting my problems with this.  However, we are now experiencing a problem during the automatic upgrade from 0.0.6 to 0.0.7.

**oc get csv** yields

NAME                                           DISPLAY                          VERSION                 REPLACES                                       PHASE
group-sync-operator.v0.0.6                     Group Sync Operator              0.0.6                                                                  Replacing
group-sync-operator.v0.0.7                     Group Sync Operator              0.0.7           group-sync-operator.v0.0.6            Pending

When issuing the command 

**oc describe csv group-sync-operator.v0.0.7 **

we receive the following error:

  Requirement Status:
    Group:    apiextensions.k8s.io
    Kind:     CustomResourceDefinition
    Message:  CRD is present and Established condition is true
    Name:     groupsyncs.redhatcop.redhat.io
    Status:   Present
    Uuid:     aba35d5c-3d49-4f2d-8bac-433b3e238ace
    Version:  v1beta1
    Dependents:
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["get","list","watch","create","update","patch","delete"],"apiGroups":[""],"resources":["configmaps"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["get","update","patch"],"apiGroups":[""],"resources":["configmaps/status"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  namespaced rule:{"verbs":["create","patch"],"apiGroups":[""],"resources":["events"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  cluster rule:{"verbs":["get","list","watch"],"apiGroups":[""],"resources":["secrets"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  cluster rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["redhatcop.redhat.io"],"resources":["groupsyncs"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  cluster rule:{"verbs":["get","patch","update"],"apiGroups":["redhatcop.redhat.io"],"resources":["groupsyncs/status"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  cluster rule:{"verbs":["create","delete","get","list","patch","update","watch"],"apiGroups":["user.openshift.io"],"resources":["groups"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  cluster rule:{"verbs":["create"],"apiGroups":["authentication.k8s.io"],"resources":["tokenreviews"]}
      Status:   NotSatisfied
      Version:  v1beta1
      Group:    rbac.authorization.k8s.io
      Kind:     PolicyRule
      Message:  cluster rule:{"verbs":["create"],"apiGroups":["authorization.k8s.io"],"resources":["subjectaccessreviews"]}
      Status:   NotSatisfied
      Version:  v1beta1
    Group:      
    Kind:       ServiceAccount
    Message:    Policy rule not satisfied for service account
    Name:       default
    Status:     PresentNotSatisfied
    Version:    v1
Events:         <none>

Can you suggest a possible resolution to this?

Thank you very much,

Michael

**Comment by sabre1041** [comment]
Hi @MichaelGoldsbie 

This appears to be related to the migration to Operator SDK 1.0 where a dedicated SA is no longer being used to run the operator. New installations of the operator have worked without issue. If you delete the `GroupConfig` custom resource and uninstall the operator, you should be able to install the updated version and then reapply the `GroupConfig`. Since the operator does not set the `ownerReferences` field of the group, existing synchronized groups will not be affected as maintenance to the operator is performed.

**Comment by sabre1041** [comment]
closing due to age
