### ISSUE TITLE
AD/LDAP upgrade from 0.0.6 to.. ?

### ISSUE THREAD

**Issue by ElCoyote27** [redhat-cop/group-sync-operator#69]
Hi,

I'm using v0.0.6 to add AD to my OCP 4.x clusters. I'm struggling to figure out how to adapt the instructions to do the same on upstream without using a 'make deploy'.

On 0.0.6, this was as simple as:
```
cd ${PATH_SCRIPT}/group-sync-operator
oc ${OC_ARGS} apply -f deploy/crds/redhatcop.redhat.io_groupsyncs_crd.yaml
oc ${OC_ARGS} apply -n group-sync-operator -f deploy/service_account.yaml
oc ${OC_ARGS} apply -n group-sync-operator -f deploy/clusterrole.yaml
oc ${OC_ARGS} apply -n group-sync-operator -f deploy/clusterrole_binding.yaml
oc ${OC_ARGS} apply -n group-sync-operator -f deploy/role.yaml
oc ${OC_ARGS} apply -n group-sync-operator -f deploy/role_binding.yaml
oc ${OC_ARGS} apply -n group-sync-operator -f deploy/operator.yaml

oc ${OC_ARGS} apply -f ${PATH_SCRIPT}/krynn-ad-oauth-group-sync-operator.yaml

```

Is 'make deploy' the only supported way to do this?

**Comment by sabre1041** [comment]
@ElCoyote27 this is due to alignment to Operator SDK 1.0

Id recommend using the OperatorHub deployment method

**Comment by ElCoyote27** [comment]
Makes sense, where could I read about deploying the group sync operator using the Operator SDK specifically?
Thank you,

**Comment by sabre1041** [comment]
The Operator SDK docs have a [Golang Tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/) that I'd recommend checking out

**Comment by ElCoyote27** [comment]
Do you think that following something like these steps would work with the group sync operator?
https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.1/html-single/service_telemetry_framework_1.1/index#creating-a-namespace

**Comment by sabre1041** [comment]
You can follow the local developer setup as per the documentation in the `README.md`

**Comment by sabre1041** [comment]
Closing issue as it has been resolved
