### ISSUE TITLE
add support for LDAP provider

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/group-sync-operator#7]

**Comment by ddreggors** [comment]
LDAP is more that one provider as I recall, there is raw LDAP as in RFC 2307, Active Directory, and Augmented Active Directory correct? Or is this issue only addressing RFC 2307?

**Comment by ddreggors** [comment]
For clarity I am referring to "as documented"

https://docs.openshift.com/container-platform/4.3/authentication/ldap-syncing.html

**Comment by sabre1041** [comment]
@ddreggors the goal of integrating an LDAP provider is to emulate the existing LDAP synchronization feature currently found in OpenShift
