### ISSUE TITLE
add support for okta provider

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/group-sync-operator#8]

**Comment by jaysonwor** [comment]
Has support for OKTA been integrated now?

**Comment by sabre1041** [comment]
@jaysonwor no this is not currently yet implemented

**Comment by Jmainguy** [comment]
See https://github.com/redhat-cop/group-sync-operator/pull/79 for a implementation of it.

**Comment by sabre1041** [comment]
Implemented as part of v0.0.11
