### ISSUE TITLE
Add support for additional architectures (ppc64le)

### ISSUE THREAD

**Issue by dmc5179** [redhat-cop/group-sync-operator#85]
Add support for additional architectures like ppc64le.

**Comment by sabre1041** [comment]
@dmc5179 multiarch support has been added. can you validate if the new features resolves this issue?

**Comment by dmc5179** [comment]
Definitely. I'll reach out to the customer that has the power HW and OpenShift 4 cluster today. Thank you.

**Comment by sabre1041** [comment]
Closing issue as multiarch support has been added. Please open a new issue if there are any challenges still being faced
